
# Functions :

a.shape - Array dimensions ,
len(a) - length of array,
b.dim - Number of array Dimensions ,
e.size - Number of array elements ,
b.dtype - Data type of array elements , 
b.astype(int) - Convert on array to differrent type  


In [15]:
import numpy as np
a= [[30,40,20],[40,30,60]]

# creating a numpy array

arr = np.array(a)
print(arr)
print("shape of the aray",arr.shape)  # rows,columns
print(len(a))  # numbere of listed values
print("size of the elements :",np.size(arr)) # number of elements
print("type of the variable:",type(arr))   #type of the variable
print("Data type of the array : ",arr.dtype)  #data type of array
print(arr.astype(float))  # conversion of variable

[[30 40 20]
 [40 30 60]]
shape of the aray (2, 3)
2
size of the array : 6
type of the array : <class 'numpy.ndarray'>
Data type of the array :  int32
[[30. 40. 20.]
 [40. 30. 60.]]
