In [12]:
import numpy as np

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
# numpber of columns must be same in each row 

print(arr[0:2,0:3])


[[10 20 30]
 [50 60 70]]


In [11]:
arr2  = np.array([10,20,30,40])
print(arr2[:])

[10 20 30 40]


In [17]:
print("shape of the array :",np.shape(arr))
print("size of the array :",np.size(arr))
print("Number of dimensions :",np.ndim(arr))
print("data type :" ,arr.dtype)

shape of the array : (3, 4)
size of the array : 12
Number of dimensions : 2
data type : int32
